#!/bin/sh

zhrlogo=/home/pn/zhr/rozkaz.tmac/zhr.eps

indent() {
  prev=1

  while read -r line
  do
    # if run .CZUWAJ macro, end indentation
    if echo $line | grep '^.CZUWAJ'>/dev/null; then
      while [ $prev -gt 1 ]; do
        echo ".RE"
        prev=$(($prev-1))
      done
      echo $line
      continue
    fi

    if echo $line | grep -P '^[0-9]+\.([0-9]+\.)* ' > /dev/null; then
      number=`echo $line | cut -d' ' -f1`
      rest=`echo $line | cut -d' ' -f2-`
      num_of_dots=`echo $number | grep -o '\.' | wc -l`
      [ $num_of_dots -gt $prev ] && echo ".RS"
      [ $num_of_dots -lt $prev ] && echo ".RE"
      indent=$(($num_of_dots*2))
      echo ".IP $number $indent\n$rest"
      prev=$num_of_dots
    else
      echo $line
    fi
  done < /dev/stdin
}

(cat << EOF
.\" Margines górny
.nr HM 0.5i
.\" Margines dolny
.nr FM 1.5i
.\" Margines lewy
.po 1.2i

.\" Wielkość czcionki i wielkość linii
.nr PS 12
.nr VS 14
.fp - R NimbusRoman-Regular
.fp - B NimbusRoman-Bold
.fp - I NimbusRoman-Italic

.ds CH
.ds CF \v'-0.3i'\l'6.05i'
.ds RF \v'1'Strona %

.de DRUŻYNA
.ds LH \\\\\$*
.ds CH \v'0.3'\l'6.05i'
.EPS $zhrlogo R 800 800
.sp -4
.br
.ll 5i
.ft B
.ad l
.ps 14
.vs 16
ZWIĄZEK HARCERSTWA RZECZYPOSPOLITEJ
.sp 0.1
.ps \n(PS)
.vs \n(VS)
\\\\\$*
.ft R
.sp -0.8
\l'5i'
.sp 1.2
.br
.ll 6i
.nr HM 1.2i
..
.
.de DATA
.ad r
\\\\\$*
.br
.ad b
..
.
.de ROZKAZ
.ad c
.sp 3
.ps 16
.ft B
Rozkaz \\\\\$*
.ft R
.ps \n(PS)
.br
.ad b
.sp 2
..
.
.de CYTAT
.sp 1
.LP
.ft I
\\\\\$1
.ft R
.sp 0.5
.ad r
.ft I
~ \\\\\$2
.ft R
.br
.ad b
.sp 1
..
.
.de CZUWAJ
.sp 1
.ad c
.ft B
Czuwaj!
.ft R
.br
.ad b
.sp 1
..
.
EOF
# cat $1) | sed 's/^\([0-9]\+\.\([0-9]\.\)*\) /\.IP \1\n/' | pic | roff -ms | pdf
cat $1 | indent) | roff -ms -meps | post | ps2pdf - -
