#!/bin/sh

indent() {
  prev=1

  while read -r line
  do
    # if run .CZUWAJ macro, end indentation
    if echo $line | grep '^.CZUWAJ'>/dev/null; then
      while [ $prev -gt 1 ]; do
        echo ".RE"
        prev=$(($prev-1))
      done
      echo $line
      continue
    fi

    if echo $line | grep -P '^[0-9]+\.([0-9]+\.)* ' > /dev/null; then
      number=`echo $line | cut -d' ' -f1`
      rest=`echo $line | cut -d' ' -f2-`
      num_of_dots=`echo $number | grep -o '\.' | wc -l`
      [ $num_of_dots -gt $prev ] && echo ".RS"
      [ $num_of_dots -lt $prev ] && echo ".RE"
      indent=$(($num_of_dots*2))
      printf ".IP $number $indent\n$rest\n"
      prev=$num_of_dots
    else
      echo $line
    fi
  done < /dev/stdin
}

cat $1 | indent | neatroff -mrozkaz | neatpost | ps2pdf - -
