#!/bin/sh

zhrlogo=/home/pn/zhr/rozkaz.tmac/zhr.eps

indent() {
  prev=1

  while read -r line
  do
    # if run .CZUWAJ macro, end indentation
    if echo $line | grep '^.CZUWAJ'>/dev/null; then
      while [ $prev -gt 1 ]; do
        echo ".RE"
        prev=$(($prev-1))
      done
      echo $line
      continue
    fi

    if echo $line | grep -P '^[0-9]+\.([0-9]+\.)* ' > /dev/null; then
      number=`echo $line | cut -d' ' -f1`
      rest=`echo $line | cut -d' ' -f2-`
      num_of_dots=`echo $number | grep -o '\.' | wc -l`
      [ $num_of_dots -gt $prev ] && echo ".RS"
      [ $num_of_dots -lt $prev ] && echo ".RE"
      indent=$(($num_of_dots*2))
      echo ".IP $number $indent\n$rest"
      prev=$num_of_dots
    else
      echo $line
    fi
  done < /dev/stdin
}

(cat << EOF
.\" Margines górny
.nr HM 0.2i
.\" Margines dolny
.po 1.2i

.\" Wielkość czcionki i wielkość linii
.nr PS 12
.nr VS 14

.de DRUŻYNA
.EPS $zhrlogo R 800 800
.sp -4
.br
.ft B
.ad l
.ps 14
.vs 16
ZWIĄZEK HARCERSTWA RZECZYPOSPOLITEJ
.sp 0.1
.ps \n(PS)
.vs \n(VS)
\\\\\$*
.sp 1
.ft R
.PS
line 6
.PE
.sp 1
..
.
.de DATA
.ad r
\\\\\$*
.ad b
..
.
.de ROZKAZ
.ad c
.sp 3
.ps 16
.ft B
Rozkaz \\\\\$*
.ft R
.ps \n(PS)
.ad b
.sp 2
..
.
.de CYTAT
.sp 1
.LP
.ft I
\\\\\$1
.ft R
.sp 0.5
.ad r
.ft I
~ \\\\\$2
.ft R
.br
.ad b
.sp 1
..
.
.de CZUWAJ
.sp 1
.ad c
.ft B
Czuwaj!
.ft R
.br
.ad b
.sp 1
..
.
EOF
# cat $1) | sed 's/^\([0-9]\+\.\([0-9]\.\)*\) /\.IP \1\n/' | pic | roff -ms | pdf
cat $1 | indent) | pic | roff -ms -meps | post | ps2pdf - -
